### ISSUE TITLE
[BUG] Support exe/msi for compatibility with wider windows platforms

### ISSUE THREAD

**Issue by dtantono** [ferraridamiano/ConverterNOW#228]
**Describe the bug**

**To Reproduce**
1. Go to https://github.com/ferraridamiano/ConverterNOW/releases/download/v4.0.1/converternow-windows.msix
2. Click on the file
3. See error (This app package’s publisher certificate could not be verified. Contact your system administrator or the app developer to obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A))

**Expected behavior**
I know msix is fine. But, it will be better if this app also packaged with msi or exe as well to make the installation easier and not everyone like Windows store and also it help many people with older Windows platforms such as Windows 7

**Screenshots / gif**

**Device**
- Device type: Windows 10
- OS version: 22h2
- Device type: [e.g. Google Pixel 6, Galaxy S21]

**Additional context**

**Comment by ferraridamiano** [comment]
The warning is because of the certificate. It is fine, you can install it anyway by accepting it. I do not plan to support windows version prior to 10. They are not supported by Microsoft too. Even the flutter team do not guarantee that flutter apps on Windows versions below 10 to work (they are classified as "best effort"). If you want to use the app on Windows 7 you can still compile it from code. If you are struggling in this process I'm here to help!
