### ISSUE TITLE
Features & Improvements

### ISSUE THREAD

**Issue by realgooseman** [ferraridamiano/ConverterNOW#265]
Hi @ferraridamiano,

Very useful cross-platform app. Well done.
I have a few improvements I would like to share. Let me know what you think.

### **Windows > remember last window position**
On Windows 11 (with 4K monitor), every time I open ConverterNOW the window shows up semi-expanded on the same top left side of the screen which is annoying. Making the app remember the last position and window size would be great.

### **Hide units or properties**
Adding an option to hide certain units on specific properties or hide full properties would be great for personalizing the experience and clean the interface of unused properties.

### **Custom themes**
Currently, on Android and Windows the theme is dynamic I think.
Are color theme presets possibly considered for future versions ?

**Comment by ferraridamiano** [comment]
Hello @realgooseman

1. I'm not used to Windows, I'm not even sure about how the windows management works. Here I ask for contributions from the community with a Windows PC
2. Good point
3. This would be a good first contribution since it would be quite easy and fun to do

I encourage you to open separate issues for the different points. This is to make the search easier
