### ISSUE TITLE
(Feature) Adding Finance Tools

### ISSUE THREAD

**Issue by fux0r2009** [ferraridamiano/ConverterNOW#32]
Hi @ferraridamiano again 

I would like to also propose to add a Financial tools to make the app more useful like the following: 

**- Unite Price:** to calculate the price of a unity product from the Price and quantity 
**- Sales Tax:** taking as input the price, tax, and a method (add or substract) and give the output: Final price, and tax amount
**- Tip:** taking as input the Bill, People, and the Tip (15% default) and give the output: Final Bill, Cost per Person and Tip amount
**- Loan:** taking as input the Loan, Rate(per Yr%), and the Period(in Years or Months) and give the output: Monthly Pay, Total Pay and Interest
**- Interest:** Simple and compound interest.

If this could be implemented It would be very helpful and very cool!

Best Regards

**Comment by ferraridamiano** [comment]
Hi again @fux0r2009 and thanks for all your suggestions!
My plan for the future is to also add a tools section in the app with all these things and much more. However I don't have too much time to work on this. I can work on this project just few hours a week.
I will close this issue for now because I first need to structure the tools section as mentioned in issue #6.
Regards!

**Comment by avipars** [comment]
@fux0r2009 agreed, https://unitmeasure.xyz/ has the tip calculator covered, as for the other features... they would be great in  either app (unfortunately, I don't know dart/flutter too well) . Focus is primarily on java/kotlin

**Comment by ferraridamiano** [comment]
Hi @avipars, please avoid to do marketing here. This isn't the rigth place, I'm sorry.
