### ISSUE TITLE
Calculator improvement

### ISSUE THREAD

**Issue by ferraridamiano** [ferraridamiano/ConverterNOW#64]
We should improve the calculator:
- create a model of the calculator and separate it from the UI
- setup a test suite
- migrate from the depracted raisedbutton to elevatedButton

**Comment by trymeouteh** [comment]
This apps reminds me of All-In-One Calculator which is a good app but I have not been able to use it in years since I degoogled my phone. Thank you for making this app and releasing it on F-Droid

https://play.google.com/store/apps/details?id=all.in.one.calculator

Please make the calculator more like the calculator in All-In-One Calculator. This way Convert Now can essentially be an open source alternative to All-In-One Calculator

**Comment by ferraridamiano** [comment]
Thank you @trymeouteh! I don't want to replicate others people's app. This is just a side project for me and I'm open to new contributors. Sadly, this is not my main work.

**Comment by trymeouteh** [comment]
The app is already pretty much like the All-In-One-Calcuator when it comes to features, all that is needs is a calculator with more features which will make this app the same as All-In-One-Calcuator but open source.
